server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 86400
  error:
    whitelabel:
      enabled: true
    include-stacktrace: never

spring:
  main:
    banner-mode: off
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    hibernate:
      jdbc:
        lob:
          non_contextual_creation: true
      ddl-auto: none
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration
    defaultSchema: shogun
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5555/shogun?currentSchema=shogun
    username: shogun
    password: shogun
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
    password: pass

keycloak:
  auth-server-url: http://localhost:8000/auth
  realm: SpringBootKeycloak
  resource: shogun-app
  public-client: true
  ssl-required: external
  principal-attribute: preferred_username
  enable-basic-auth: true
#  security-constraints:
#    - authRoles:
#      - user
#    - securityCollections:
#      - pattern:
#        - /customers/*

keycloakauth:
  username: admin
  password: shogun
  master-realm: master
  admin-client: admin-cli

upload:
  file:
    supportedContentTypes:
      - application/json
      - application/pdf
      - application/xml
      - application/zip
      - text/comma-separated-values
      - text/plain
      - text/xml
  image:
    thumbnailSize: 100
    supportedContentTypes:
      - image/bmp
      - image/gif
      - image/jpeg
      - image/png
      - image/svg+xml
      - image/tiff
