name: Test SHOGun

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  license-headers:

    runs-on: ubuntu-22.04

    steps:

    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Check License Header
      uses: apache/skywalking-eyes@v0.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  commitlint:

    runs-on: ubuntu-22.04

    steps:

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v5

  mvn-test:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 17
        java-package: jdk
        architecture: x64

    - name: Handle caching of maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Test SHOGun with Maven
      env:
        KEYCLOAK_HOST: localhost
      run: mvn -B test

  startup:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 17
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17
          java-package: jdk
          architecture: x64

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Run mvn install
        run: mvn install --log-file mvn.out.txt

      - name: Clone shogun-docker
        run: git clone https://github.com/terrestris/shogun-docker
        working-directory: ../

      - name: Checkout specific commit to ensure reproducibility
        run: git checkout d02a88ad9b1583b1f7c05407d944b5ff91585765
        working-directory: ../shogun-docker

      - name: Set environment variables
        run: ./setEnvironment.sh create -y
        working-directory: ../shogun-docker

      - name: Show environment variables
        run: cat .env
        working-directory: ../shogun-docker

      - name: Start containers
        run: docker-compose up -d
        working-directory: ../shogun-docker

      - name: Inspect network
        run: docker network inspect shogun-docker_default
        working-directory: ../shogun-docker

      - name: Check if application has started
        run: ./scripts/wait.sh

      - name: Docker logs
        if: always()
        run: docker-compose logs
        working-directory: ../shogun-docker

      - name: Maven output
        if: always()
        run: cat mvn.out.txt
